setwd("/home/thibault/Documents/CROISEMENTS/E149_plaque01_220817_C8")

PROQ12 <- read.table("Proq12.txt", header=TRUE, sep="\t")
PROQ13 <- read.table("Proq13.txt", header=TRUE, sep="\t")
PROQ73 <- read.table("Proq73.txt", header=TRUE, sep="\t")
PROQ74 <- read.table("Proq74.txt", header=TRUE, sep="\t")
PROQ75 <- read.table("Proq75.txt", header=TRUE, sep="\t")
PROQ77 <- read.table("Proq77.txt", header=TRUE, sep="\t")
PROQ80 <- read.table("Proq80.txt", header=TRUE, sep="\t")
PROQ81 <- read.table("Proq81.txt", header=TRUE, sep="\t")
PROQ83 <- read.table("Proq83.txt", header=TRUE, sep="\t")
PROQ88 <- read.table("Proq88.txt", header=TRUE, sep="\t")
PROQ93 <- read.table("Proq93.txt", header=TRUE, sep="\t")

joint <- merge(PROQ12, PROQ13, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint1 <- merge(PROQ73, joint, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint2 <- merge(PROQ74, joint1, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint3 <- merge(PROQ75, joint2, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint4 <- merge(PROQ77, joint3, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint5 <- merge(PROQ80, joint4, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint6 <- merge(PROQ81, joint5, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint7 <- merge(PROQ83, joint6, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint8 <- merge(PROQ88, joint7, by.x="Sample.Name", by.y="Sample.File", all=TRUE)
joint9 <- merge(PROQ93, joint8, by.x="Sample.Name", by.y="Sample.File", all=TRUE)

write.table(joint9, "jointure_Penicillium.txt", sep="\t",quote=FALSE, row.names=FALSE)

edit(joint)
dim(L2206)
head(L2206)
